version: "3.8"
services:
  order-placement-db:
    container_name: orderplacement_database
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orderplacementdb
    volumes:
      - "C:\\Volumes\\postgres\\order_placement:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    networks:
      - test_network
    hostname: order-db

  customer-db:
    container_name: customer_service_database
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: customerdb
    volumes:
      - "C:\\Volumes\\postgres\\customer:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - test_network
    hostname: customer-db

  authentication-db:
    container_name: authentication_service_database
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authentication
    volumes:
      - "C:\\Volumes\\postgres\\authentication:/var/lib/postgresql/data"
    ports:
      - "5434:5432"
    networks:
      - test_network
    hostname: authentication-db


  pgadmin:
    container_name: pgadimn-4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - test_network

  discovery-server:
    build: ServiceRegistry
    container_name: service-registry-container
    ports:
      - "8761:8761"
    networks:
      - test_network
    hostname: service-registry

  order-placement:
    build: OrderPlacementService
    container_name: order-placement-container
    depends_on:
      - order-placement-db
      - discovery-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/orderplacementdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - test_network

  customer-service:
    build: CustomerService
    container_name: customer-service-container
    depends_on:
      - customer-db
      - discovery-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-db:5432/customerdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "8083:8080"
    networks:
      - test_network

  authentication-service:
    build: AuthenticationService
    container_name: auth-service-container
    depends_on:
      - authentication-db
      - discovery-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://authentication-db:5432/authentication
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "8084:8080"
    networks:
      - test_network
  api-gateway:
    build: ApiGateway
    container_name: api-gateway-container
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - test_network

networks:
  test_network:
