spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: '*'
            maxAge: 30

      routes:
        - id: OrderPlacementService
          uri: lb://ORDERPLACEMENTSERVICE
          predicates:
            - Path=/orders/**, /swagger-ui/**
          filters:
#              - AuthenticationFilter
        - id: CustomerService
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/customers/**, /swagger-ui/**
          filters:
#              - AuthenticationFilter

        - id: AuthenticationService
          uri: lb://AUTHENTICATIONSERVICE
          predicates:
            - Path=/auth/**
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  main:
    web-application-type: reactive

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 7200000